import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bcv Euro",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon-16x16.png', // Reference to an icon file in app/icon.png
    apple: '/icon512_maskable.png', // Reference to an Apple icon file
    shortcut: '/icon512_maskable.png', // Reference to the favicon.ico
  },
  manifest: "/manifest.json"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">


        <head>
        {/* Manifest */}
        <link rel="manifest" href="/manifest.json?v=4" />

        {/* Android */}
        <meta name="mobile-web-app-capable" content="yes" />

        {/* iOS */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Bcv Euro" />

        {/* Iconos */}
        <link rel="apple-touch-icon" href="/android-chrome-192x192.png" />
        <link rel="icon" sizes="192x192" href="/android-chrome-192x192.png" />
      </head>




      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
